### ISSUE TITLE
Unblock domains for Certificate validation for Apple devices

### ISSUE THREAD

**Issue by thomasmerz** [cedws/apple-telemetry#27]
https://support.apple.com/en-us/HT210060 says:
> **Certificate validation**
Apple devices must be able to connect to the following hosts to validate digital certificates used by the hosts in this article.

I checked my Pi-hole and found that there are some/two domains/hosts being blocked in your blocklist which shouldn't be blocked:

```
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   ocsp.apple.com
 Match found in https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry:
   valid.apple.com
```

Please check and remove them from your blocklist. Thank you!

https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry 
> \# Blocks Apple telemetry and tracking but won't break your device
\# Sourced from https://github.com/adversarialtools/apple-telemetry/blob/master/blacklist
\# Originally hosted at https://github.com/llacb47/apple-telemetry/blob/master/blacklist

**Comment by cedws** [comment]
The project is looking for maintainers. You can send a PR for this if you like and I'll review it.

**Comment by thomasmerz** [comment]
What is a maintainer expected to do? I would agree to start as a **collaborator** to help you maintaining and **working on some issues**. Are there more doings that I don't have in my mind as a maintainer for this project?

**Comment by cedws** [comment]
To maintain the blocklist and releases of it. For example, the Actions pipeline is broken right now so a new release won't be published. I don't have the time to fix it.

**Comment by thomasmerz** [comment]
Thanks, for your trust. I'll try my best with the actions pipeline for releasing… and working on some issues (I'm also working 100% but I'm confident to find some time in the near future)…

**Comment by cedws** [comment]
No problem. You have write access to `master` so feel free to hack away. Pull requests would be good though just to get some secondary eyes on changes.

If you need anything from me you can message me at `cedw@pm.me`.
