### ISSUE TITLE
Remove Apple location service from blacklist

### ISSUE THREAD

**Issue by frankherchet** [cedws/apple-telemetry#33]
I use your list in my pihole. But I had to whitelist the following regex to use Apple Maps.

`ls(.\|-)apple.com`

I would recommend to remove those matches to be able to use the service.

**Comment by thomasmerz** [comment]
Uh, I found it and also whitelisted your @frankherchet regex. Thanks!

**Comment by thomasmerz** [comment]
Closing as PR #34 has been already merged.

**Comment by thomasmerz** [comment]
Made an issue https://github.com/liamengland1/mischosts/issues/42 and PR https://github.com/liamengland1/mischosts/pr/43 at another apple-related blocklist that I additionally use because your @frankherchet RegEx didn't work for me as https://regex101.com/r/psI4Hg/1 shows 🤷🏼‍♂️

**Comment by thomasmerz** [comment]
ℹ️ Correct/fixed RegEx is: `ls(.|-)apple.com` - see https://regex101.com/r/UEzcxP/1
